version: '3.8'

services:
  postgres:
    image: postgres:13.3
    env_file: ./config/pg_database/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  backend:
    env_file: ./config/backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000

#  migrate:
#    volumes:
#      - ./solution:/app
#    env_file: ./config/solution/.env
#    build:
#      context: ./solution/
#      dockerfile: Dockerfile_migrate
#    command:
#      - /bin/bash
#      - -c
#      - |
#       alembic revision --autogenerate
#       alembic upgrade head
#    depends_on:
#      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  redis:
    driver: local